mod-name: KerbalAtomics
package:
  include-dependencies: true  # Include dependencies in the package
  included-gamedata:
    - KerbalAtomics
  included-support:  # Include these root-level files in packages
    - readme.txt
    - changelog.txt
dependencies:  # Configure dependencies
  ModuleManager:
    version: 4.1.3
    location: s3
  B9PartSwitch:
    version: 2.16.0
    location: s3
  CommunityResourcePack:
    version: 1.3.0
    location: s3
  DynamicBatteryStorage:
    tag: 2.1.6
    location: github
    repository: ChrisAdderley/DynamicBatteryStorage
  DeployableEngines:
    tag: 1.2.1
    location: github
    repository: ChrisAdderley/DeployableEngines
  CryoTanks:
    tag: 1.5.0
    location: github
    repository: ChrisAdderley/CryoTanks
deploy:
  SpaceDock:
    enabled: true  # activate/deactivate this deployment script
    mod-id: 710  # The Spacedock mod ID for deployment
  CurseForge:
    enabled: true  # activate/deactivate this deployment script
    mod-id: 241040  # The CurseForge mod ID for deployment
  GitHub:
    enabled: true  # activate/deactivate this deployment script
